<a href="https://colab.research.google.com/github/SambhavDjain/Ml_Projects/blob/main/TensorFlow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

#Every matrix is a tensor but not every tensors are  matrix

#Rank of tensor means the no of dimensions

In [28]:
S = tf.constant(5)
S
tf.shape(S),tf.rank(S),tf.size(S)

(<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [30]:
V = tf.constant([1,2,3,4,5])
V
V.ndim
tf.shape(V),tf.rank(V),tf.size(V)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>)

In [29]:
M = tf.constant([[1,3],[4,5],[6,7]])
M
tf.shape(M),tf.rank(M),tf.size(M)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [19]:
T = tf.constant([[[1,2],[3,5],[5,6]]])
T
tf.shape(T),tf.rank(T),tf.size(T)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 5],
        [5, 6]]], dtype=int32)>

In [47]:
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])
tensor1
tensor2


<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.5831698 , 0.2215004 , 0.23657954, ..., 0.5568533 , 0.8110198 ,
        0.7171099 ],
       [0.05928802, 0.26840377, 0.47587645, ..., 0.5289341 , 0.62610257,
        0.69821036],
       [0.3402146 , 0.14764023, 0.95250213, ..., 0.44892168, 0.21191919,
        0.8835138 ],
       [0.2425617 , 0.11993206, 0.23601592, ..., 0.99891996, 0.7786603 ,
        0.12292767],
       [0.92812943, 0.3816805 , 0.8607886 , ..., 0.3175894 , 0.872839  ,
        0.6698694 ]], dtype=float32)>

In [50]:
Matrix_mul = tf.matmul(tensor1 ,tf.transpose(tensor2))
Matrix_mul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.937805, 79.31862 , 72.33655 , 77.861496, 77.81325 ],
       [72.83988 , 74.22507 , 70.1508  , 77.001945, 77.27977 ],
       [74.181435, 74.53183 , 67.5733  , 75.97419 , 77.7177  ],
       [75.21057 , 74.56216 , 72.45743 , 77.76497 , 76.82483 ],
       [76.88472 , 78.35257 , 73.23671 , 81.3023  , 80.18059 ]],
      dtype=float32)>

In [66]:
Dot_pdt = tf.tensordot(tensor1,tensor2,axes=[[1],[1]])
Dot_pdt

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.39813 , 74.62955 , 73.75058 , 78.92976 , 75.06874 ],
       [69.06598 , 72.72127 , 71.78369 , 73.295296, 72.05461 ],
       [69.93716 , 70.73422 , 69.80247 , 74.26539 , 69.5395  ],
       [75.323586, 78.18501 , 76.942474, 77.297356, 75.95474 ],
       [71.97155 , 74.85087 , 70.52992 , 75.114044, 72.31033 ]],
      dtype=float32)>

In [70]:
Ran_tens = tf.random.uniform(shape= [224,224,3])
Ran_tens

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.04374456, 0.98272276, 0.6002557 ],
        [0.38521123, 0.13945019, 0.6886053 ],
        [0.85382235, 0.84953666, 0.5012145 ],
        ...,
        [0.37702143, 0.6958202 , 0.6380347 ],
        [0.80712676, 0.53542197, 0.00483787],
        [0.49300408, 0.44516826, 0.46199584]],

       [[0.5295373 , 0.24433589, 0.18849647],
        [0.8405175 , 0.38360786, 0.46415424],
        [0.41191328, 0.08674765, 0.69899285],
        ...,
        [0.2020073 , 0.47837627, 0.92774296],
        [0.1863327 , 0.80794585, 0.17051888],
        [0.14130998, 0.06010962, 0.87057173]],

       [[0.7566469 , 0.9061649 , 0.10365593],
        [0.1801033 , 0.8383893 , 0.5631218 ],
        [0.9914789 , 0.80316806, 0.6934719 ],
        ...,
        [0.5594959 , 0.4984603 , 0.34737504],
        [0.18525887, 0.91724205, 0.92670894],
        [0.7492353 , 0.60467434, 0.57448375]],

       ...,

       [[0.99979115, 0.7924899 , 0.05167353],
        [0.53

In [104]:
tf.reduce_min(Ran_tens), tf.reduce_max(Ran_tens)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.2755393981933594e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999991655349731>)

In [110]:
Ran_tens = tf.random.uniform(shape= [1,224,224,3])
tf.squeeze(Ran_tens)
#In this Dimension 1  got removed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.285887  , 0.08787119, 0.6453334 ],
        [0.8955898 , 0.7570729 , 0.58016324],
        [0.9644264 , 0.48660862, 0.9455806 ],
        ...,
        [0.99465334, 0.8191378 , 0.9530878 ],
        [0.48987246, 0.30111432, 0.00761986],
        [0.57174146, 0.5919055 , 0.10571599]],

       [[0.6504817 , 0.72584283, 0.8400301 ],
        [0.7251663 , 0.7587054 , 0.9193344 ],
        [0.4079007 , 0.30509174, 0.3091396 ],
        ...,
        [0.32371688, 0.68990684, 0.9623804 ],
        [0.06476891, 0.06393254, 0.54948103],
        [0.31844997, 0.56796265, 0.7623161 ]],

       [[0.6833267 , 0.09872675, 0.7868285 ],
        [0.5579289 , 0.47953534, 0.6741018 ],
        [0.79443204, 0.38795376, 0.6427573 ],
        ...,
        [0.2321291 , 0.3571688 , 0.77326727],
        [0.8635273 , 0.48500502, 0.31759298],
        [0.2444495 , 0.603606  , 0.04616308]],

       ...,

       [[0.85185146, 0.7676054 , 0.42209566],
        [0.48

In [8]:
tensor = tf.constant([0,1,2,3,4,5900,6,7,8,78],dtype = tf.int32)
tf.reduce_max(tensor)
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [11]:
tensor = tf.constant([0,1,2,3,4,5900,6,7,8,78],dtype = tf.int32)
tf.one_hot(tensor,depth = 16)

<tf.Tensor: shape=(10, 16), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>

In [12]:
import tensorflow as tf

# Original tensor
my_tensor = tf.constant([3, 15, 2, 8, 6, 9, 12, 7, 1, 5], dtype=tf.int32)

# One-hot encode it
one_hot_encoded = tf.one_hot(my_tensor, depth=16)

# Print the result
print("One-hot encoded tensor:\n", one_hot_encoded.numpy())


One-hot encoded tensor:
 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
