<a href="https://colab.research.google.com/github/SambhavDjain/Ml_Projects/blob/main/tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors

In [4]:
  import tensorflow as tf
  print(tf.__version__)

2.18.0


In [5]:
#Create tensors with tf.constants()
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
#Create the no of dimensions of a tensor
scalar.ndim


0

In [7]:
#Create the vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#checking dimension of vector
vector.ndim

1

In [9]:
#Create the matrix more than 1 dimensions
matrix =tf.constant([[10,8],[8,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 8, 10]], dtype=int32)>

In [10]:
#create another matrix
another_matrix = tf.constant([[10.,4.],
                              [4.,5.],
                              [5.,34.]], dtype = tf.float16) #specify the data type with dtype parameter
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 4.,  5.],
       [ 5., 34.]], dtype=float16)>

In [11]:
#Dimension of anotehr_matrix
another_matrix.ndim

2


*what we have done so far*

*scalar* =  a single no

*Vector*  = a no with directions (wind speed and direction)

*Matrix* = 2d array of no

*Tensor* = a n-d array (n can be no, a 0-d tensor is scalar and a-1 is vector)

###Creating tensors with tf.variable

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
#Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#Lets change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#by trying .assign
changeable_tensor[0].assign(8)
changeable_tensor

In [ ]:
#Lets change the unchanegeable tensor
unchangeable_tensor[0].assign(8)
unchangeable_tensor


###Create random tensors

Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
#Create two random tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
##Are they equal
random_1,random_2,random_1 == random_2


###Shuffle the order of the elements in a tensor

In [ ]:
 not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
##not_shuffled.ndim

tf.random.shuffle(not_shuffled)

In [ ]:
##shuffle non shuffled tensor
tf.random.set_seed(42) #Reproducible: Same output every run if the TensorFlow version and code are unchanged.
tf.random.shuffle(not_shuffled,seed =42) # No global seed, but op-level seed set

####Rules for the random seed tensors

If both the global and operational seeds are set booth seed are used in conjuction to determine the random sequence



In [ ]:
non_shuffled = tf.constant([[10,4],[5,6],[7,8]])
tf.random.shuffle(non_shuffled,seed = 42) #using op level seed
tf.random.set_seed(42) #global level seed no change happen
tf.random.shuffle(non_shuffled)


###Other ways to make tensors

In [ ]:
 #create the tensors of all ones(1)
 tf.ones([5,10])

In [ ]:
 #create the tensors of all zeros(0)
 tf.zeros([3,5])

##Turn Numpy arrays into tensors

The maine difference between Numpy arrays and Tensorflow tensors is that tensors can be run on the GPU(much faster for numerical computing)

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)#Create a numpy array between 1 to 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# Y = tf.constant(vector) # non-capital for vector


In [ ]:
A = tf.constant(numpy_A, shape=([2,3,4]))
A


###Getting info from Tensors
When dealing with tensors you probably want to be aware of the following attributes:

**Shape**

 **Rank**

 **Axis of Dimension**

 **Size**

In [ ]:
#create a rank 4 tensor (4 dimension )
rank_4_tensor = tf.zeros(shape=[2,3,4,5]) #2 total , 3 is in between 2, 4 rows each , 5 columns each
rank_4_tensor


In [ ]:
#Get various attributes of our Tensors
print("Datatype of every element",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor :",rank_4_tensor.shape)
print("Elements along 0 axis/index:",rank_4_tensor.shape[0])
print("Elements along last axis/index:",rank_4_tensor.shape[-1])
print("Total no of elements in our tensor:",tf.size(rank_4_tensor))
print("Total no of elements in our tensor:",tf.size(rank_4_tensor).numpy())

###Indexing Tensors
Tensors can be indexed just like python lists.

In [ ]:
list_1 = [1,2,3,4]
list_1[:2]

In [ ]:
#get the fisrt 2 elements of each dimennsion
rank_4_tensor[:2,:2,:2,:2]


In [ ]:
#Get the first element from  each dimension from each indeax except the final
rank_4_tensor[:1,:1,:1]

In [ ]:
rank_2_tensor =tf.constant([[10,2],[23,8]])
rank_2_tensor
rank_2_tensor.shape,rank_2_tensor.ndim

In [ ]:
#Getting last item of each row  of our rank 2 tensor
rank_2_tensor[:,1]

In [ ]:
#Ading on extra dimension to our rank 3 tensor
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis] ## or [...,tf.newaxis]
rank_3_tensor

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis =-1) #-1 means expand final axis axis also refers to index -1 refers to the last



In [ ]:
tf.expand_dims(rank_2_tensor,axis = 1)#expand the 1 axis

In [ ]:
tf.expand_dims(rank_2_tensor,axis = 0)#expand the 0 axis

###Manipulating Tensors (tensor opearations)
Basic operations
`+` , `-` , `*`,  `/`.

In [ ]:
#Add values to tensor using addition opearator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10


In [ ]:
#original tensor reemains unchanges
tensor

In [ ]:
#Multiplication also works
tensor *10

In [ ]:
#Tensorflow built-in version
tf.multiply(tensor,10)


###Matrix Multiplication

In ml, it is the most important tensor operation

There are teo rules our tensor (or matrices )need to fulfill if we going to matrix multiply them:

1.The inner dimension must match

2.The resulting matrix has the shape of the outer dimensions

In [ ]:
print(tensor)

In [ ]:
tensor * tensor

In [ ]:
#Matrix multiplication using ppython operator "@"
tensor @ tensor

In [ ]:
tensor.shape

In [ ]:
#Create a tensor(3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
#create another (3,2)tensor
Y =tf.constant([[7,8],
                [9,10],
                [11,12]])
X ,Y

In [ ]:
#Built-in command
tf.matmul(X,Y)

In [ ]:
#Multiplying the above (3,2)tensor
X @ Y

In [ ]:
#chnging the shape of Y
tf.reshape(Y,shape=(2,3))

In [ ]:
#multiply  X by resaped Y
X@tf.reshape(Y,shape=[2,3])

In [ ]:
#on rehsape X
tf.reshape(X,shape=(2,3))

In [ ]:
#multiply by rehsape X
tf.reshape(X,shape=(2,3)) @ Y

In [ ]:
#Transpose the Matrix
tf.transpose(X)

In [ ]:
#Multiply by a transpose matrix
tf.transpose(X) @ Y

📚 **Resource**: info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

###The Dot Product
Matrix Multiplication is also reffered as dot product
also perform using :



*   `tf.matmul()`
*   `tf.tensordot()`
*   `@`





In [ ]:
#Perform the dot product on  X , Y (requires X or Y to be transposed )
tf.tensordot(tf.transpose(X),Y,axes=)

### Change the datatype of the tensor

In [ ]:
#the version
tf.__version__


In [ ]:
#Create a new tensor with default datatypes (float32)
B = tf.constant([1.7,4.40])
B.dtype


In [ ]:
C = tf.constant([7,10])
C.dtype

In [ ]:
#Change from float32 to float16 (reduced precision)
D =tf.cast(B,dtype=tf.float16)
D , D.dtype

In [ ]:
#Change from int32 to float32
E1 = tf.cast(C,dtype = tf.float32)
E1

In [ ]:
E = tf.cast(E1,dtype=tf.int32)
E

In [ ]:
E_float16= tf.cast(E,dtype=tf.float16)
E_float16

###Aggregating tensors

Aggregating tensors = condensing them from multiple values down to small amounts of values.

In [ ]:
#Getting the absolute values
D = tf.constant([-5,-20])
D

In [ ]:
#Get the absolute values
tf.abs(D) #Take -values and turn them into positive/'

Let's go through the following forms of aggregation:

* Get the minimum
* Get  the maximum
* Get the mean of tensor
* Get the sum of a tensor


In [21]:
import numpy as np


In [ ]:
E = tf.constant(np.random.randint(0,100, size = 50))
E

In [ ]:
#Find the minimum
tf.reduce_min(E)

In [ ]:
#Find the Maximum
tf.reduce_max(E)

In [ ]:
#find the mean
tf.reduce_mean(E)

In [ ]:
#Find the sum
tf.reduce_sum(E)

In [ ]:
#Find the variance
#tf.reduce_variance(E) not worked
#tf.math.reduce_variance(E) # not even this

##Using a lib tensorflow_probability

In [ ]:
#find variance
tf.math.reduce_variance(tf.cast(E,dtype = tf.float32))

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
#Find the standard Deviation
#In this use of float to find the std as it not found in int type
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

##Find the Positional maximum nad minimum

In [ ]:
#Find a new tensor for finding positional minimum nad maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f


In [ ]:
#Find the positional maximum
tf.argmax(f) #Returns the index having the largest value across tensor


In [ ]:
#index on our largest value position
f[tf.argmax(f)] #Max value in tensor f

In [ ]:
#Max value in tensor
tf.reduce_max(f)

In [ ]:
# Aree they equal
f[tf.argmax(f)]== tf.reduce_max(f)

In [ ]:
#For Minimum
tf.argmin(f)

In [ ]:
#knowing about the no
f[tf.argmin(f)]

###Squeezing a tensor (Removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]),shape = [1,1,1,1,50])
G

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed # it removes the no of brackets from the given tensor
#or for its proffesional basis remveos dimension of size 1 from shape of tensor


 ### One hot Encoding Tensors
 One-hot encoding is a way to convert categorical values (like labels or classes) into a format that machine learning models can understand — using binary vectors.

In [ ]:
#create a list of indices
some_list  = [0,1,2,3,] #Could be red ,green , blue , purple

#One hot encode our list of indices
tf.one_hot(some_list,depth=4)

In [ ]:
#Specify coustom values for hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="I also like to dance")
#

### Squaring , log , square root

In [15]:
#Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [16]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [17]:
#Find the Squareroot (gives error as its not applicable on int)
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [18]:
#Find the Squareroot
tf.sqrt(tf.cast(H ,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [19]:
#Find the log ( log - Computes natural logarithm of x element-wise.)
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
TensorFlow interacts beautifully with Numpy arrays


In [22]:
#Convert a tensor directly from Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [27]:
#Convert back tensor to numpy array
np.array(J), type(np.array(J))


(array([ 3.,  7., 10.]), numpy.ndarray)

In [28]:
#Convert tensor J to Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)